name = "Skymoss"
author = "jerezereh"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad20e6a713d622f7e431f3c3e3ef2f1c137ae3f71f386373865818743fd626c2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
