name = "Skymoss"
author = "jerezereh"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1bef49332b22d03a2815255a7adc389f0974bffc0dfe903a8607af45ef6a1120"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
