name = "Skymoss"
author = "jerezereh"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb857b68a83317bfa3362febe9b23599156c2f9079ce36c5f848751b97c445a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.241"
